-- SQL Script to update book image URLs on the production server
BEGIN;

UPDATE "Books" SET "ImageUrl" = '/images/books/Aktif Çamur Sürecinin Tasarım Uygulamaları Cilt I.jpeg' WHERE "Name" = 'Atıksu Arıtma Sistemlerinin Tasarım Esasları C-I';
UPDATE "Books" SET "ImageUrl" = '/images/books/Aktif Çamur Sürecinin Tasarım Uygulamaları Cilt II.jpeg' WHERE "Name" = 'Atıksu Arıtma Sistemlerinin Tasarım Esasları C-II';
UPDATE "Books" SET "ImageUrl" = '/images/books/anaerobik arıtma.jpg' WHERE "Name" = 'Anaerobik Arıtma';
UPDATE "Books" SET "ImageUrl" = '/images/books/analitik geometri.jpg' WHERE "Name" = 'Analitik Geometri';
UPDATE "Books" SET "ImageUrl" = '/images/books/arıtma çamurlarının işlenmesi.jpg' WHERE "Name" = 'Arıtma Çamurlarının İşlenmesi';
UPDATE "Books" SET "ImageUrl" = '/images/books/atmosfer kimyası.jpg' WHERE "Name" = 'Atmosfer Kimyası';
UPDATE "Books" SET "ImageUrl" = '/images/books/atıksu arıtma sistemlerinin tasarım esasları C-II.jpg' WHERE "Name" = 'Atıksu Arıtma Sistemlerinin Tasarım Esasları C-II';
UPDATE "Books" SET "ImageUrl" = '/images/books/açık işletme tekniği.jpg' WHERE "Name" = 'Açık İşletme Tekniği';
UPDATE "Books" SET "ImageUrl" = '/images/books/Beton.jpeg' WHERE "Name" = 'Beton';
UPDATE "Books" SET "ImageUrl" = '/images/books/Bilgisayar Programlama.jpeg' WHERE "Name" = 'Bilisayar Programlama (matlab Uygulamalı)';
UPDATE "Books" SET "ImageUrl" = '/images/books/Diferansiyel Denklemler.jpeg' WHERE "Name" = 'Diferansiyel Denklemler';
UPDATE "Books" SET "ImageUrl" = '/images/books/elektrik makinalarının temel ilkeleri.jpg' WHERE "Name" = 'Elektrik  Makinalarının Temel İlkeleri';
UPDATE "Books" SET "ImageUrl" = '/images/books/Endüstriyel Atık Suların Yönetimi.jpeg' WHERE "Name" = 'Endüstriyel atık suların yönetilmesi';
UPDATE "Books" SET "ImageUrl" = '/images/books/Fiziksel Modeller.jpeg' WHERE "Name" = 'Fiziksel Modeller';
UPDATE "Books" SET "ImageUrl" = '/images/books/French For Engineers.jpeg' WHERE "Name" = 'Fransızca';
UPDATE "Books" SET "ImageUrl" = '/images/books/inşaat mühendisleri için malzeme bilgisi.jpg' WHERE "Name" = 'Malzeme Bilgisi (İnş.Müh.İçin.)';
UPDATE "Books" SET "ImageUrl" = '/images/books/işletme yönetimi ve organizasyonu.jpg' WHERE "Name" = 'İşletme Yöntemi ve Organizasyonu';
UPDATE "Books" SET "ImageUrl" = '/images/books/Jeofizikte Sinyal Analizi.jpeg' WHERE "Name" = 'Jeofizik Sinyal Analizi';
UPDATE "Books" SET "ImageUrl" = '/images/books/jeotermalde yerbilimsel uygulamalar.jpg' WHERE "Name" = 'Jeotermalde Yerbilimsel  Uygulamalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/kaldırma makinaları.jpg' WHERE "Name" = 'Kaldırma Makinaları';
UPDATE "Books" SET "ImageUrl" = '/images/books/katı atık toplama taşıma ve bertaraf sistemlerinin eniyilenmesi ve ekonomisi.jpg' WHERE "Name" = 'Katı Atık Toplama Taş. Bertaraf sis.';
UPDATE "Books" SET "ImageUrl" = '/images/books/kaya mekaniği.jpg' WHERE "Name" = 'Kaya Mekaniği';
UPDATE "Books" SET "ImageUrl" = '/images/books/kayaçların radyometrik yaş tayininin ana yöntemleri.jpg' WHERE "Name" = 'Kayaçların Radyometrik Yaş Tayininin Ana Yöntemleri';
UPDATE "Books" SET "ImageUrl" = '/images/books/Kil Mineralleri.jpeg' WHERE "Name" = 'Kil Mineralleri (Ders Notları)';
UPDATE "Books" SET "ImageUrl" = '/images/books/kimya laboratuvarı deneyleri.jpg' WHERE "Name" = 'Genel Kimya için Lab.Deneyleri Kitap';
UPDATE "Books" SET "ImageUrl" = '/images/books/kömür teknolojisi.jpg' WHERE "Name" = 'Kömür Teknolojisi';
UPDATE "Books" SET "ImageUrl" = '/images/books/kömür.jpg' WHERE "Name" = 'Kömür';
UPDATE "Books" SET "ImageUrl" = '/images/books/Kıyı Mühendisliğinde Sayısal Uygulamalar.jpeg' WHERE "Name" = 'Kıyı Mühendisliğinde  Sayısal Uygulamalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/maden işletme ekonomisi.jpg' WHERE "Name" = 'Maden işletme Ekonomisi';
UPDATE "Books" SET "ImageUrl" = '/images/books/maden jeolojisi uygulama klavuzu.jpg' WHERE "Name" = 'Maden Jeolojisi Uygulama Kılavuzu';
UPDATE "Books" SET "ImageUrl" = '/images/books/maden mühendisleri için ölçme tekniği.jpg' WHERE "Name" = 'Maden Mühendisleri için Ölçme Tekniği';
UPDATE "Books" SET "ImageUrl" = '/images/books/madenlerde nakliyat.jpg' WHERE "Name" = 'Madenlerde Nakliyat';
UPDATE "Books" SET "ImageUrl" = '/images/books/madenlerde su arıtımı ve pompalar.jpg' WHERE "Name" = 'Madenlerde Su atımı ve Pompalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/matematik I (lineer cebir).jpg' WHERE "Name" = 'Matematik-I (Lineer Cebir)';
UPDATE "Books" SET "ImageUrl" = '/images/books/mineraloji.jpg' WHERE "Name" = 'Mineroloji-Genel Mineroloji (Cilt I )';
UPDATE "Books" SET "ImageUrl" = '/images/books/Mühendislik Jeolojisi.jpeg' WHERE "Name" = 'Mühendislik Jeolojisi';
UPDATE "Books" SET "ImageUrl" = '/images/books/sayısal çözümleme ve örnekler.jpg' WHERE "Name" = 'Sayısal Çözümleme ve Örnekler';
UPDATE "Books" SET "ImageUrl" = '/images/books/sistem dinamiği ve otomatik kontrol.jpg' WHERE "Name" = 'Sistem Dinamiği ve Otomatik Kontrol';
UPDATE "Books" SET "ImageUrl" = '/images/books/Su Kuvveti Su Yapıları.jpeg' WHERE "Name" = 'Su Kuvveti Su yapıları Cilt IX';
UPDATE "Books" SET "ImageUrl" = '/images/books/su kuvveti tesislerinde sayısal örnekler.jpg' WHERE "Name" = 'Sukuvveti tes.Sayısal Örnekle';
UPDATE "Books" SET "ImageUrl" = '/images/books/Tekstil Mekaniğinin Temelleri.jpeg' WHERE "Name" = 'Tekstil Mekaniğinin Temelleri';
UPDATE "Books" SET "ImageUrl" = '/images/books/tünel ve kuyu açma.jpg' WHERE "Name" = 'Tünel Ve Kuyu Açma';
UPDATE "Books" SET "ImageUrl" = '/images/books/volkaniklastik kayaçlar.jpg' WHERE "Name" = 'Volkanik Lastik Kayaclar';
UPDATE "Books" SET "ImageUrl" = '/images/books/yapı ve deprem mühendisliğinde matris yöntemler.jpg' WHERE "Name" = 'Yapı ve Deprem Mühendisliğinde Matris Yöntemler';
UPDATE "Books" SET "ImageUrl" = '/images/books/Yeraltı Havalandırması.jpeg' WHERE "Name" = 'Yer Altı Havalandırması';
UPDATE "Books" SET "ImageUrl" = '/images/books/çevre mühendiliğinde mikrobiyolojik uygulamalar.jpg' WHERE "Name" = 'Çevre Mühendisliğinde Mikrobiyolojik Uygulamalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/çevre mühendisliğinde fiziksel - kimyasal temel süreçler.jpg' WHERE "Name" = 'Çevre Mühendisliğinde Fiziksel- Kimyasal Temel Süreçler';
UPDATE "Books" SET "ImageUrl" = '/images/books/çevre ühendisliğinde biyoprosesler.jpg' WHERE "Name" = 'Çevre Mühendisliğinde Biyoprosesler';
UPDATE "Books" SET "ImageUrl" = '/images/books/örmecilik esasları.jpg' WHERE "Name" = 'Örmecilik Esasları';
UPDATE "Books" SET "ImageUrl" = '/images/books/üretim fonksiyonları.jpg' WHERE "Name" = 'Üretim Fonksiyonları';
UPDATE "Books" SET "ImageUrl" = '/images/books/üretim planama.jpg' WHERE "Name" = 'Üretim Planlama';

COMMIT;
