-- SQL Script to update book image URLs to slugified safe format on the production server
BEGIN;

UPDATE "Books" SET "ImageUrl" = '';

UPDATE "Books" SET "ImageUrl" = '/images/books/acik-isletme-teknigi.jpg' WHERE "Name" = 'Açık İşletme Tekniği';
UPDATE "Books" SET "ImageUrl" = '/images/books/aktif-camur-surecinin-tasarim-uygulamalari-cilt-i.jpeg' WHERE "Name" = 'Aktif Çamur Sürecinin Tasarım Uygulamaları Cilt I';
UPDATE "Books" SET "ImageUrl" = '/images/books/aktif-camur-surecinin-tasarim-uygulamalari-cilt-ii.jpeg' WHERE "Name" = 'Aktif Çamur Sürecinin Tasarım Uygulamaları Cilt II';
UPDATE "Books" SET "ImageUrl" = '/images/books/anaerobik-aritma.jpg' WHERE "Name" = 'Anaerobik Arıtma';
UPDATE "Books" SET "ImageUrl" = '/images/books/analitik-geometri.jpg' WHERE "Name" = 'Analitik Geometri';
UPDATE "Books" SET "ImageUrl" = '/images/books/aritma-camurlarinin-islenmesi.jpg' WHERE "Name" = 'Arıtma Çamurlarının İşlenmesi';
UPDATE "Books" SET "ImageUrl" = '/images/books/ataturk-ve-aydinlanma.jpeg' WHERE "Name" = 'Atatürk ve Aydınlanma';
UPDATE "Books" SET "ImageUrl" = '/images/books/atiksu-aritma-sistemlerinin-tasarim-esaslari-c-ii.jpg' WHERE "Name" = 'Atıksu Arıtma Sistemlerinin Tasarım Esasları C-II';
UPDATE "Books" SET "ImageUrl" = '/images/books/atmosfer-kimyasi.jpg' WHERE "Name" = 'Atmosfer Kimyası';
UPDATE "Books" SET "ImageUrl" = '/images/books/bilgisayar-programlama.jpeg' WHERE "Name" = 'Bilisayar Programlama (matlab Uygulamalı)';
UPDATE "Books" SET "ImageUrl" = '/images/books/cevre-muhendiliginde-mikrobiyolojik-uygulamalar.jpg' WHERE "Name" = 'Çevre Mühendisliğinde Mikrobiyolojik Uygulamalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/cevre-muhendisliginde-fiziksel-kimyasal-temel-surecler.jpg' WHERE "Name" = 'Çevre Mühendisliğinde Fiziksel- Kimyasal Temel Süreçler';
UPDATE "Books" SET "ImageUrl" = '/images/books/cevre-uhendisliginde-biyoprosesler.jpg' WHERE "Name" = 'Çevre Mühendisliğinde Biyoprosesler';
UPDATE "Books" SET "ImageUrl" = '/images/books/diferansiyel-denklemler.jpeg' WHERE "Name" = 'Diferansiyel denklemler';
UPDATE "Books" SET "ImageUrl" = '/images/books/elektrik-makinalarinin-temel-ilkeleri.jpg' WHERE "Name" = 'Elektrik  Makinalarının Temel İlkeleri';
UPDATE "Books" SET "ImageUrl" = '/images/books/endustriyel-atik-sularin-yonetimi.jpeg' WHERE "Name" = 'Endüstriyel atık suların yönetilmesi';
UPDATE "Books" SET "ImageUrl" = '/images/books/fizik-laboratuvari-ii-deney-kitapcigi.jpeg' WHERE "Name" = 'Fizik Lab II';
UPDATE "Books" SET "ImageUrl" = '/images/books/fiziksel-modeller.jpeg' WHERE "Name" = 'Fiziksel Modeller';
UPDATE "Books" SET "ImageUrl" = '/images/books/french-for-engineers.jpeg' WHERE "Name" = 'Fıransızca';
UPDATE "Books" SET "ImageUrl" = '/images/books/gecmisten-gunumuze-dunyada-su-yapilari.jpeg' WHERE "Name" = 'Geçmişten Günümüze Dünya Su Yapıları';
UPDATE "Books" SET "ImageUrl" = '/images/books/giysi-kalipciligi-i.jpeg' WHERE "Name" = 'Giysi Kalıpçılığı-1';
UPDATE "Books" SET "ImageUrl" = '/images/books/i-s-ve-zaman-etudu.jpeg' WHERE "Name" = 'İş ve zaman etüdü  ';
UPDATE "Books" SET "ImageUrl" = '/images/books/i-zmir-in-kurtulusu-ve-yuzbasi-serafettin.jpeg' WHERE "Name" = 'Üçünçü  Kılıç';
UPDATE "Books" SET "ImageUrl" = '/images/books/insaat-muhendisleri-icin-malzeme-bilgisi.jpg' WHERE "Name" = 'Malzeme Bilgisi (İnş.Müh.İçin.)';
UPDATE "Books" SET "ImageUrl" = '/images/books/isletme-yonetimi-ve-organizasyonu.jpg' WHERE "Name" = 'İşletme Yöntemi ve Organizasyonu';
UPDATE "Books" SET "ImageUrl" = '/images/books/jeofizikte-sinyal-analizi.jpeg' WHERE "Name" = 'Jeofizik Sinyal Analizi';
UPDATE "Books" SET "ImageUrl" = '/images/books/jeotermalde-yerbilimsel-uygulamalar.jpg' WHERE "Name" = 'Jeotermalde Yerbilimsel  Uygulamalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/kaldirma-makinalari.jpg' WHERE "Name" = 'Kaldırma Makinaları';
UPDATE "Books" SET "ImageUrl" = '/images/books/kati-atik-toplama-tasima-ve-bertaraf-sistemlerinin-eniyilenmesi-ve-ekonomisi.jpg' WHERE "Name" = 'Katı Atık Toplama Taş. Bertaraf sis.';
UPDATE "Books" SET "ImageUrl" = '/images/books/kaya-mekanigi.jpg' WHERE "Name" = 'Kaya Mekaniği';
UPDATE "Books" SET "ImageUrl" = '/images/books/kayaclarin-radyometrik-yas-tayininin-ana-yontemleri.jpg' WHERE "Name" = 'Kayaçların Radyometrik Yaş Tayininin Ana Yöntemleri';
UPDATE "Books" SET "ImageUrl" = '/images/books/kil-mineralleri.jpeg' WHERE "Name" = 'Kil Mineralleri (Ders Notları)';
UPDATE "Books" SET "ImageUrl" = '/images/books/kim-1016-organik-kimya-uygulama-deneyleri.jpeg' WHERE "Name" = 'Genel kimya için Lab.Deneyleri';
UPDATE "Books" SET "ImageUrl" = '/images/books/kimya-laboratuvari-deneyleri.jpg' WHERE "Name" = 'Genel kimya için Lab.Deneyleri Kitap';
UPDATE "Books" SET "ImageUrl" = '/images/books/kiyi-muhendisliginde-sayisal-uygulamalar.jpeg' WHERE "Name" = 'Kıyı Mühendisliğinde  Sayısal Uygulamalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/komur-teknolojisi.jpg' WHERE "Name" = 'Kömür Teknolojisi';
UPDATE "Books" SET "ImageUrl" = '/images/books/komur.jpg' WHERE "Name" = 'Kömür';
UPDATE "Books" SET "ImageUrl" = '/images/books/maden-isletme-ekonomisi.jpg' WHERE "Name" = 'Maden işletme Ekonomisi';
UPDATE "Books" SET "ImageUrl" = '/images/books/maden-jeolojisi-uygulama-klavuzu.jpg' WHERE "Name" = 'Maden Jeolojisi Uygulama kılavuzu';
UPDATE "Books" SET "ImageUrl" = '/images/books/maden-muhendisleri-icin-olcme-teknigi.jpg' WHERE "Name" = 'Maden Mühendisleri için Ölçme Tekniği';
UPDATE "Books" SET "ImageUrl" = '/images/books/madenlerde-nakliyat.jpg' WHERE "Name" = 'Madenlerde Nakliyat';
UPDATE "Books" SET "ImageUrl" = '/images/books/madenlerde-su-aritimi-ve-pompalar.jpg' WHERE "Name" = 'Madenlerde Su atımı ve Pompalar';
UPDATE "Books" SET "ImageUrl" = '/images/books/matematik-i-lineer-cebir.jpg' WHERE "Name" = 'Matematik-I (Lineer Cebir)';
UPDATE "Books" SET "ImageUrl" = '/images/books/mineraloji.jpg' WHERE "Name" = 'Mineroloji-Genel Mineroloji (Cilt I )';
UPDATE "Books" SET "ImageUrl" = '/images/books/muhendis-ve-mimar-sinan.jpeg' WHERE "Name" = 'Mühendis ve Mimar Sinan';
UPDATE "Books" SET "ImageUrl" = '/images/books/muhendislik-jeolojisi.jpeg' WHERE "Name" = 'Mühendislik Jeolojisi';
UPDATE "Books" SET "ImageUrl" = '/images/books/ormecilik-esaslari.jpg' WHERE "Name" = 'Örmecilik Esasları';
UPDATE "Books" SET "ImageUrl" = '/images/books/potansiyel-teori-ve-jeofizik-uygulamalari.jpeg' WHERE "Name" = 'Potansiyel Teori Jeofizik Uygulamaları';
UPDATE "Books" SET "ImageUrl" = '/images/books/sayisal-cozumleme-ve-ornekler.jpg' WHERE "Name" = 'Sayısal Çözümleme ve Örnekler';
UPDATE "Books" SET "ImageUrl" = '/images/books/sistem-dinamigi-ve-otomatik-kontrol.jpg' WHERE "Name" = 'Sistem Dinamiği ve Otomatik Kontrol';
UPDATE "Books" SET "ImageUrl" = '/images/books/staj-defteri.jpg' WHERE "Name" = 'Staj Defteri';
UPDATE "Books" SET "ImageUrl" = '/images/books/su-kaynaklarinin-i-yilestirilmesi.jpeg' WHERE "Name" = 'Su Kaynaklarını Geliştirilmesi';
UPDATE "Books" SET "ImageUrl" = '/images/books/su-kuvveti-su-yapilari.jpeg' WHERE "Name" = 'Su Kuvveti Su yapıları Cilt IX';
UPDATE "Books" SET "ImageUrl" = '/images/books/su-kuvveti-tesislerinde-sayisal-ornekler.jpg' WHERE "Name" = 'Sukuvveti tes.Sayısal Örnekle';
UPDATE "Books" SET "ImageUrl" = '/images/books/tasiyici-sistemlerin-dinamik-analizi.jpeg' WHERE "Name" = 'Taşıyıcı Sistemlerin Dinamik Analizi';
UPDATE "Books" SET "ImageUrl" = '/images/books/tekstil-mekaniginin-temelleri.jpeg' WHERE "Name" = 'Tekstil Mekaniğinin Temelleri';
UPDATE "Books" SET "ImageUrl" = '/images/books/tunel-ve-kuyu-acma.jpg' WHERE "Name" = 'Tünel Ve Kuyu Açma';
UPDATE "Books" SET "ImageUrl" = '/images/books/turk-devrim-tarihi-i.jpeg' WHERE "Name" = 'Türk Devrim Tarihi';
UPDATE "Books" SET "ImageUrl" = '/images/books/uretim-fonksiyonlari.jpg' WHERE "Name" = 'Üretim Fonksiyonları';
UPDATE "Books" SET "ImageUrl" = '/images/books/uretim-planama.jpg' WHERE "Name" = 'Üretim Planlama';
UPDATE "Books" SET "ImageUrl" = '/images/books/volkaniklastik-kayaclar.jpg' WHERE "Name" = 'Volkanik lastik Kayaclar';
UPDATE "Books" SET "ImageUrl" = '/images/books/yapi-ve-deprem-muhendisliginde-matris-yontemler.jpg' WHERE "Name" = 'Yapı ve Deprem Mühendisliğinde Matris Yöntemler';
UPDATE "Books" SET "ImageUrl" = '/images/books/yeralti-havalandirmasi.jpeg' WHERE "Name" = 'Yer altı havalandırması';
UPDATE "Books" SET "ImageUrl" = '/images/books/yeralti-maden-makineleri-ve-mekanizasyonu.jpg' WHERE "Name" = 'Yer altı Maden Makinaları Ve Mekanizasyonu';

COMMIT;
